name: mypy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Change this to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run mypy
      run: |
        python -m mypy --strict --check-untyped-defs --exclude build/lib .
